### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by mayoralink** [Protocentral/Pulse#2]
The following classes do not exist on the program's scope:

HelpWidget 
HeaderButton
MessageBox 
SPO2_cal

**Comment by VenkateshBhat** [comment]
Could you please elaborate your issue a little more?

**Comment by mayoralink** [comment]
In openview_oximeter.pde, HelpWidget, HeaderButton, MessageBox, and SPO2_cal classes are missing from  ControlP5 library, making the file unable to run.

**Comment by VenkateshBhat** [comment]
Which version of processing are you using? Recommended is Processing 3.2.1.
Have you placed the library in appropriate directory? i.e. user->documents->Processing -> library->ControlP5.
And open the IDE in administrative mode if you are not the administrator.

**Comment by mayoralink** [comment]
Using Processing v3.2.3

All libraries have been appropriately installed in the specified directories from the instructions.

![image](https://cloud.githubusercontent.com/assets/13774690/20814238/798d4f94-b7de-11e6-919f-d3ad784c3b9a.png)

![image](https://cloud.githubusercontent.com/assets/13774690/20814330/c7f08548-b7de-11e6-8ef8-4eb6f249ff2e.png)

![image](https://cloud.githubusercontent.com/assets/13774690/20814379/0254b7fe-b7df-11e6-84b1-c82e4689ebd7.png)

![image](https://cloud.githubusercontent.com/assets/13774690/20814428/34b353f4-b7df-11e6-93ef-62137e48e460.png)

**Comment by VenkateshBhat** [comment]
No its user defined so it should be in the local sketch directory.
It seems to be ContolP5 library is not properly installed(path could be)
Please check whether its added to Tools--> Add Tool -->Libraries --> (tick mark on ControlP5)
If it is not added  please do add.
![controlp5](https://cloud.githubusercontent.com/assets/6176131/20824022/26bfc14c-b87f-11e6-829d-cf7e4eb31fc1.png)
and and import the library
![importlibrary](https://cloud.githubusercontent.com/assets/6176131/20824102/b759c34c-b87f-11e6-98d9-9f46cd954339.png)
This could solve your issue.

**Comment by VenkateshBhat** [comment]
Have you fixed the issue?

**Comment by mayoralink** [comment]
Issue has been resolved.
