### ISSUE TITLE
error: macro "max" requires 2 arguments, but only 1 given

### ISSUE THREAD

**Issue by HNeumeier** [Protocentral/Pulse#7]
i get a compilation error with the Arduino Uno
error: macro "max" requires 2 arguments, but only 1 given
can you help me.

**Comment by VenkateshBhat** [comment]
@HNeumeier  Please attach the error screen shot

**Comment by HNeumeier** [comment]
![bildschirmfoto vom 2017-12-10 16-31-51](https://user-images.githubusercontent.com/33512064/33806385-c087b744-ddc7-11e7-9343-912790c42919.png)

**Comment by VenkateshBhat** [comment]
Thanks for sharing, there are two sections Firmware and Ui. 
Please run the firmware in Arduino(https://github.com/Protocentral/Pulse/tree/master/Software/Arduino)
and UI using Processing IDE(https://github.com/Protocentral/Pulse/tree/master/Software/Processing). In case if you do not have Processing installed , download the IDE from here https://processing.org/download/

**Comment by HNeumeier** [comment]
Thanks for your Help, now everything is working.
